module.exports = {
  categoryObjKeys: ["main", "sub"],
  mainCategories: [
    "all",
    "fashion",
    "food-beverage-alcohol",
    "sports-outdoor",
    "diet-health",
    "cosmetic-beauty",
    "smartphone-tablet-pc",
    "tv-audio-camera",
    "home-appliances",
    "furniture-interior",
    "daily-necessities-accessories",
    "pet",
    "handmade",
    "musical-instrument",
    "game",
    "toy-hobby",
    "baby-kids-maternity",
    "car-bike",
    "cd-music",
    "dvd",
    "book-magazine-cartoon",
    "ticket",
  ],
  subCategories: [
    "ladies",
    "mens",
    "food",
    "beverage",
    "alcohol",
    "sports",
    "outdoor",
    "smartphone",
    "tablet-pc",
    "tv",
    "audio",
    "camera",
    "home-appliances",
    "cooking-appliances",
    "health-appliances",
    "beauty-appliances",
    "air-conditioning",
    "video-game",
    "trading-card",
    "card-game",
    "board-game",
    "car",
    "bike",
    "bicycle",
    "book",
    "magazine",
    "cartoon",
  ],
  platforms: ["mercari", "rakuma", "paypay"],
  productStatuses: [
    "all",
    "brand_new",
    "almost_unused",
    "no_scratches_or_stains",
    "slight_scratches_or_stains",
    "noticeable_scratches_or_stains",
  ],
  salesStatuses: ["all", "selling", "soldout"],
  deliveryCosts: ["all", "free", "required"],
  sortOrders: ["asc", "desc"],
};
