steps:
  - id: 'Create .env file'
    name: ubuntu
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo PORT=8080 >> .env &&
        echo PROD_PYTHON_SCRIPT="~/api/app/python/index.py" >> .env &&
        echo ".env >>> " $(cat .env) &&
        mv .env /custom_volume
    volumes:
      - name: 'custom'
        path: '/custom_volume'
    # dir: 'workspace'

  - id: 'Integrate files into api directory'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - -c
      - |
        mkdir api &&
        mv /custom_volume/.env ./api &&
        ls * | grep -v "api" | xargs mv -t ./api &&
        echo "api dir contents >>> " $(ls -la ./api)
    volumes:
      - name: 'custom'
        path: '/custom_volume'
    # dir: 'workspace'

  - id: 'Transfer api directory with scp'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'compute',
        'scp',
        '--project',
        'markets-jp',
        '--zone',
        'asia-northeast1-b',
        '--port',
        '49152',
        '--recurse',
        './api',
        'markets-jp:/var/www',
      ]
    timeout: 1800s
    # dir: 'workspace'
