steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: 'ubuntu'
    args: ['bash', './cloudbuild.sh']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'compute',
        'scp',
        '--project',
        'markets-jp',
        '--zone',
        'asia-northeast1-b',
        '--port',
        '49152',
        '--recurse',
        './markets',
        'markets-jp:/home/tipotto404',
      ]
