steps:
  - id: 'Install dependencies, create .env file'
    name: node
    entrypoint: 'bash'
    args:
      - -c
      - |
        yarn install &&
        echo PORT=8080 >> .env &&
        echo PROD_PYTHON_SCRIPT="~/api/app/python/index.py" >> .env &&
        mv node_modules .env /workspace

  - id: 'Integrate files into api directory'
    name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - -c
      - |
        mkdir api &&
        mv *[^api] ./api

  - id: 'Transfer api directory with scp'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'compute',
        'scp',
        '--project',
        'markets-jp',
        '--zone',
        'asia-northeast1-b',
        '--port',
        '49152',
        '--recurse',
        './api',
        'markets-jp:~/',
      ]
    dir: 'workspace'
